project_id = "jmowninkqcfgwldyjeqo"
 
 [functions.admin-get-orders]
 verify_jwt = false
 
 [functions.admin-update-order]
 verify_jwt = false
 
 [functions.admin-delete-review]
 verify_jwt = false

 [functions.send-order-email]
 verify_jwt = false

 [functions.apply-coupon]
 verify_jwt = false

 [functions.admin-manage-sellers]
 verify_jwt = false

 [functions.fraud-check]
 verify_jwt = false

 [functions.ai-product-search]
 verify_jwt = false

 [functions.ai-generate-description]
 verify_jwt = false

 [functions.ai-product-analyzer]
 verify_jwt = false

 [functions.ai-chat]
 verify_jwt = false

 [functions.facebook-messenger-webhook]
 verify_jwt = false

 [functions.send-otp]
 verify_jwt = false

 [functions.verify-otp]
 verify_jwt = false

 [functions.admin-manage-returns]
 verify_jwt = false

 [functions.affiliate-manage]
 verify_jwt = false

 [functions.detect-ip]
 verify_jwt = false

 [functions.check-blocked-ip]
 verify_jwt = false

 [functions.checkout-create-order]
 verify_jwt = false
